name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  message-file:
    description: Path to the file containing the message to post
    required: true
    default: './message.txt'
  token:
    description: GH PAT

# Define your outputs here.
outputs:
  result:
    description: result

runs:
  using: node20
  main: dist/index.js
